In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

In [8]:
# Phase 1 — Define dataset paths

TRADER_DATA_PATH = "../data/historical_data.csv"
SENTIMENT_DATA_PATH = "../data/fear_greed_index.csv"

print("Paths Defined")

Paths Defined

In [9]:
# Phase 2 — Load datasets

trader_data = pd.read_csv(TRADER_DATA_PATH)
sentiment_data = pd.read_csv(SENTIMENT_DATA_PATH)

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

In [10]:
# View first rows of trader dataset
print("Trader Dataset Preview")
display(trader_data.head())

# View first rows of sentiment dataset
print("Sentiment Dataset Preview")
display(sentiment_data.head())

Trader Dataset Preview

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

Sentiment Dataset Preview

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [11]:
print("Trader Dataset Shape:", trader_data.shape)
print("Sentiment Dataset Shape:", sentiment_data.shape)

Trader Dataset Shape: (211224, 16)
Sentiment Dataset Shape: (2644, 4)

In [13]:
print("Trader Dataset Info")
trader_data.info()

print("\nSentiment Dataset Info")
sentiment_data.info()

Trader Dataset Info
<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  str
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), str(6)
memory usage: 24.4 MB

Sentiment Dataset Info
<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   str
 3   date            2644 non-null   str
dtypes: int64(2), str(2)
memory usage: 82.8 KB

In [15]:
print("Missing Values in Trader Dataset:")
print(trader_data.isnull().sum())

print("\nMissing Values in Sentiment Dataset:")
print(sentiment_data.isnull().sum())

Missing Values in Trader Dataset:
Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

Missing Values in Sentiment Dataset:
timestamp         0
value             0
classification    0
date              0
dtype: int64

In [16]:
print("Duplicate Rows in Trader Dataset:", trader_data.duplicated().sum())
print("Duplicate Rows in Sentiment Dataset:", sentiment_data.duplicated().sum())

Duplicate Rows in Trader Dataset: 0
Duplicate Rows in Sentiment Dataset: 0

In [17]:
# Phase 3 — Convert timestamp to datetime

trader_data['Timestamp'] = pd.to_datetime(trader_data['Timestamp'], unit='ms')

trader_data[['Timestamp']].head()

            Timestamp
0 2024-10-27 03:33:20
1 2024-10-27 03:33:20
2 2024-10-27 03:33:20
3 2024-10-27 03:33:20
4 2024-10-27 03:33:20

In [19]:
# Extract trade date

trader_data['trade_date'] = trader_data['Timestamp'].dt.date

trader_data[['Timestamp','trade_date']].tail()

                 Timestamp  trade_date
211219 2025-06-15 15:06:40  2025-06-15
211220 2025-06-15 15:06:40  2025-06-15
211221 2025-06-15 15:06:40  2025-06-15
211222 2025-06-15 15:06:40  2025-06-15
211223 2025-06-15 15:06:40  2025-06-15

In [20]:
# Convert sentiment date to datetime

sentiment_data['date'] = pd.to_datetime(sentiment_data['date']).dt.date

sentiment_data.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [21]:
# Keep only important columns

sentiment_data = sentiment_data[['date','classification']]

sentiment_data.head()

         date classification
0  2018-02-01           Fear
1  2018-02-02   Extreme Fear
2  2018-02-03           Fear
3  2018-02-04   Extreme Fear
4  2018-02-05   Extreme Fear

In [22]:
print("Trader Dataset Info After Cleaning")
trader_data.info()

print("\nSentiment Dataset Info After Cleaning")
sentiment_data.info()

Trader Dataset Info After Cleaning
<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  str
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  datetime64[ms]
 16  trade_date        211224 non-null  object
dtypes: bool(1), datetime64[ms](1), float64(7), int64(1), object(1), str(6)
memory usage: 26.0+ MB

Sentiment Dataset Info After Cleaning
<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            2644 non-null   object
 1   classification  2644 non-null   str
dtypes: object(1), str(1)
memory usage: 41.4+ KB

In [23]:
print("Cleaned Trader Dataset")
display(trader_data.head())

print("Cleaned Sentiment Dataset")
display(sentiment_data.head())

Cleaned Trader Dataset

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,trade_date
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,2024-10-27 03:33:20,2024-10-27
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,2024-10-27 03:33:20,2024-10-27
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,2024-10-27 03:33:20,2024-10-27
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,2024-10-27 03:33:20,2024-10-27
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,2024-10-27 03:33:20,2024-10-27

Cleaned Sentiment Dataset

         date classification
0  2018-02-01           Fear
1  2018-02-02   Extreme Fear
2  2018-02-03           Fear
3  2018-02-04   Extreme Fear
4  2018-02-05   Extreme Fear

In [24]:
# Phase 4 — Merge trader data with sentiment data

merged_data = pd.merge(
    trader_data,
    sentiment_data,
    left_on='trade_date',
    right_on='date',
    how='left'
)

print("Datasets merged successfully")

Datasets merged successfully

In [25]:
merged_data.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,trade_date,date,classification
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,2024-10-27 03:33:20,2024-10-27,2024-10-27,Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,2024-10-27 03:33:20,2024-10-27,2024-10-27,Greed
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,2024-10-27 03:33:20,2024-10-27,2024-10-27,Greed
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,2024-10-27 03:33:20,2024-10-27,2024-10-27,Greed
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,2024-10-27 03:33:20,2024-10-27,2024-10-27,Greed

In [ ]:
# Check Merge Success
merged_data['classification'].value_counts()

# Check Missing Sentiment Values
print("Missing Sentiment Values:",merged_data['classification'].isnull().sum())


print("Merged Dataset Shape:", merged_data.shape)

Merged Dataset Shape: (211224, 19)

In [30]:
# View Important Columns

merged_data[
    [
        'Account',
        'Coin',
        'Side',
        'Size USD',
        'Closed PnL',
        'trade_date',
        'classification'
    ]
].head()

,Account,Coin,Side,Size USD,Closed PnL,trade_date,classification
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,BUY,7872.16,0.0,2024-10-27,Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,BUY,127.68,0.0,2024-10-27,Greed
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,BUY,1150.63,0.0,2024-10-27,Greed
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,BUY,1142.04,0.0,2024-10-27,Greed
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,BUY,69.75,0.0,2024-10-27,Greed

In [31]:
merged_data.to_csv("../data/merged_trader_sentiment_data.csv", index=False)

print("Merged dataset saved")

Merged dataset saved